DROP TABLE IF EXISTS "articles";
DROP SEQUENCE IF EXISTS articles_article_id_seq1;
CREATE SEQUENCE articles_article_id_seq1 INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1;

DROP TABLE IF EXISTS "users";
DROP SEQUENCE IF EXISTS users_user_id_seq1;
CREATE SEQUENCE users_user_id_seq1 INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1;

CREATE TABLE "public"."users" (
    "user_id" integer DEFAULT nextval('users_user_id_seq1') NOT NULL,
    "user_name" character varying(255) NOT NULL,
    "user_pwd" character varying(255) NOT NULL,
    "user_email" character varying(255) NOT NULL,
    "user_permission" smallint DEFAULT '0' NOT NULL,
    CONSTRAINT "users_pkey" PRIMARY KEY ("user_id"),
    CONSTRAINT "users_user_name_key" UNIQUE ("user_name")
) WITH (oids = false);

INSERT INTO "users" ("user_id", "user_name", "user_pwd", "user_email", "user_permission") VALUES
(1,	'romain',	'$2y$10$sDE5hEznlfKJvnMyaIv0KuMlb9fgTvr/SBq6ijj6.MHcpDWFcfv.G',	'romain@gmail.com',	2),
(2,	'vadim',	'$2y$10$rJCd5kRSw1pQcOb1On7V2O8jQfWvF7wyIBhJl/Sfd2Sk0ipcLqrKW',	'vadim@gmail.com',	1),
(3,	'nabil',	'$2y$10$mayp/jI.Isk3TISGY3Go3O.RWAz64IcLSsXyL2UDXcf9QglumtE9a',	'nabil@gmail.com',	1),
(4,	'stephanie',	'$2y$10$SidP5tW6ueqv9UZDPdxUVuFB1mu3jWZYjxxTvKV776NHajlgSCuvO',	'stephanie@gmail.com',	1);


CREATE TABLE "public"."articles" (
    "article_id" integer DEFAULT nextval('articles_article_id_seq1') NOT NULL,
    "article_title" character varying(255) NOT NULL,
    "article_content" text NOT NULL,
    "article_date" TIMESTAMP NOT NULL,
    "user_id" integer NOT NULL,
    CONSTRAINT "articles_pkey" PRIMARY KEY ("article_id"),
    CONSTRAINT "articles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(user_id) NOT DEFERRABLE
) WITH (oids = false);

INSERT INTO "articles" ("article_id", "article_title", "article_content", "article_date", "user_id") VALUES
(1,	'Lorem Ipsum 1',	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fermentum tortor venenatis neque convallis rutrum. Suspendisse mi est, blandit eget sagittis in, interdum sed erat. Aliquam erat volutpat. Nam sit amet tristique dui. Fusce ultricies, sem sit amet porta aliquet, leo ex aliquet ligula, egestas luctus neque dui sit amet urna. Donec interdum, ipsum in cursus convallis, magna libero luctus ligula, at vulputate elit quam vitae massa. Maecenas bibendum neque quis sem feugiat cursus. Sed imperdiet quis diam non tempus. Maecenas hendrerit nisl eget metus posuere ultricies. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis convallis metus sem, in iaculis quam tempus nec. Quisque iaculis dui neque, in tristique erat pretium ac. Integer at aliquam leo, vel rutrum mi. Sed vulputate urna finibus velit dapibus, eu congue risus finibus. Aenean volutpat eu diam sit amet pellentesque.

Morbi tempor non mi at ornare. Pellentesque vitae nisl orci. Pellentesque efficitur felis sit amet tincidunt scelerisque. Morbi tortor neque, aliquam in sagittis in, accumsan et dolor. Maecenas elementum non risus sit amet elementum. Nam facilisis efficitur nisi, id viverra lacus ultricies quis. Aliquam placerat non ante a sollicitudin. Etiam varius odio sit amet tellus consectetur porttitor. Suspendisse potenti. Ut ornare tempor enim, et tincidunt sapien porttitor in. Nunc vitae mollis arcu. In gravida diam id sagittis malesuada. Phasellus vel imperdiet nulla, eu tempus nisi. Sed auctor eros purus, vitae consequat lorem aliquet quis. Maecenas accumsan metus eget volutpat porta. Vivamus congue sit amet augue eu pellentesque.

Aliquam in neque id lorem semper tempus. Quisque semper elit ac tellus hendrerit sodales. Nulla quam enim, condimentum eu nulla vel, fringilla lacinia tellus. Suspendisse in dapibus tortor, a sodales nulla. Suspendisse potenti. Sed dui turpis, vestibulum sit amet nibh non, tincidunt tincidunt est. Morbi sit amet posuere lectus. Aenean eu elementum orci, sed luctus neque. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum aliquam eros id erat viverra rhoncus. Cras finibus iaculis lacus, non pulvinar risus dictum quis. Ut pharetra pulvinar dolor vitae aliquet. Vivamus pretium sit amet lorem sed egestas. Nam consectetur id nulla sed imperdiet.

Sed aliquam, arcu quis venenatis efficitur, dolor arcu venenatis purus, quis convallis erat neque sed leo. Curabitur facilisis enim arcu, quis consectetur lacus mattis non. Vestibulum mattis, metus id efficitur feugiat, risus magna placerat nulla, ut commodo ex velit vitae ligula. Donec mattis dolor quam, sed sollicitudin tortor lobortis sit amet. Fusce sed mattis ex. Nulla ultrices enim enim, ac luctus nulla elementum quis. Sed ac tortor nec elit tincidunt accumsan a quis dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas ut consectetur felis.

Fusce efficitur, nunc vel vestibulum aliquam, metus metus elementum leo, ac semper mi metus nec erat. Etiam at cursus odio. Quisque ultricies luctus neque, eget pharetra ante interdum eu. Nulla quis diam eget ipsum pulvinar congue. In tempus venenatis mollis. Suspendisse pretium fringilla tellus, vitae vulputate nibh convallis id. Vivamus ante mauris, auctor in sem quis, malesuada accumsan neque. Donec non est dignissim, interdum dolor et, pretium purus. Etiam malesuada tellus vel ullamcorper aliquet.',	'2019-03-14',	1),
(2,	'Lorem Ipsum 2',	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla pellentesque, dolor ut aliquet dictum, risus turpis semper lectus, in tempor turpis sapien eget magna. Vestibulum hendrerit elementum dignissim. Praesent posuere lectus sapien, vulputate mattis mauris lobortis a. Nulla auctor eget sapien vel aliquet. Sed cursus tellus tellus, ac viverra nisl fermentum at. Fusce eros felis, eleifend sed malesuada at, tempor ultricies est. Etiam consequat, magna in iaculis blandit, tortor enim maximus nisl, non egestas quam tortor at odio. Donec aliquam, nunc quis egestas tincidunt, felis ipsum molestie turpis, id semper tellus nulla a sapien. Pellentesque vulputate massa orci, sed aliquet velit convallis ut. Proin eget nisi posuere, eleifend sem eget, accumsan nisi. Nullam dapibus mattis ultrices. Sed id arcu dolor.

Sed finibus tellus vitae sapien placerat, non lobortis libero gravida. Curabitur blandit feugiat nisl, at imperdiet orci fringilla vel. Nunc tristique nisi et hendrerit laoreet. Mauris porttitor urna nec nisi posuere pellentesque. Quisque ac enim eu sapien ultrices imperdiet. Phasellus auctor et sapien ac lacinia. Nunc mattis semper aliquet.

Mauris scelerisque, arcu eget blandit porta, tellus lacus sollicitudin metus, convallis dapibus nunc nisl vitae ipsum. Integer quis malesuada nulla. In vitae posuere eros. Integer at lobortis nisl. Suspendisse id libero ac odio pharetra bibendum eu in nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin nunc tellus, faucibus et fermentum quis, lacinia et eros. Nullam at ligula ac lectus dictum suscipit ut id nibh. Quisque ac placerat mauris, sed elementum est. Nunc sagittis imperdiet nulla sed vehicula. Suspendisse varius diam in eros semper, eget malesuada orci vestibulum. Cras eget pretium diam.

Donec a fermentum tellus. Quisque ac suscipit diam. Donec vel turpis sit amet nisl tempus volutpat. Donec aliquet vel orci at bibendum. Donec rutrum massa sodales sagittis pulvinar. Mauris at blandit velit. Sed consectetur sed nibh nec faucibus. Suspendisse at nulla vestibulum, ultrices enim ut, eleifend risus. Nulla facilisi. Fusce luctus ipsum in nunc vestibulum mattis.

Vivamus quam dolor, vestibulum ut turpis non, sodales consequat dui. Praesent sed lectus vitae odio pulvinar volutpat. Etiam ac porta mauris. Ut nec tincidunt sapien, eu congue nunc. Nullam semper auctor arcu, non luctus mi ullamcorper ut. Pellentesque quis auctor ex, pellentesque mollis diam. Suspendisse molestie tempor tortor faucibus porttitor. Nullam mollis, purus at commodo venenatis, ex quam accumsan mi, id auctor sapien elit et tortor. Etiam enim urna, imperdiet fringilla dignissim at, volutpat et justo. Maecenas sit amet magna ac dolor pulvinar cursus a et erat. Nam sit amet nisi venenatis, venenatis odio sollicitudin, dictum nulla. Suspendisse malesuada, tellus sit amet convallis mollis, est eros rhoncus felis, ac tincidunt metus tellus ut risus. Maecenas a orci egestas, convallis turpis in, semper tortor.',	'2019-03-14',	1),
(3,	'Lorem Ipsum 3',	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tempor velit eu risus congue pretium. Praesent tempor imperdiet tellus ut sagittis. Nam eget accumsan tortor. Ut eleifend laoreet eleifend. Vivamus ut nisi massa. Sed et vulputate sapien. Curabitur suscipit leo vel mauris posuere lacinia. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

Nunc iaculis nulla quis cursus vestibulum. Nam ac vehicula nulla, eget commodo neque. Vivamus eu nunc pulvinar, suscipit tortor eu, pellentesque sapien. Maecenas purus urna, blandit volutpat lectus molestie, elementum euismod sem. Aenean maximus auctor blandit. Quisque commodo tristique est. Etiam a nisl fringilla, consequat elit in, bibendum tortor. Morbi efficitur auctor quam nec congue. Proin non nisl sed dolor sodales aliquam. Ut nec euismod ipsum. Duis consequat nisi nunc. Nam sit amet vulputate ligula.

Nullam eget risus ac ligula vulputate sollicitudin. Vivamus quis imperdiet ex. Donec sit amet pretium mi. Sed maximus lacus sed ex dignissim, a euismod ligula elementum. Sed vitae enim consequat, suscipit enim sit amet, hendrerit quam. Praesent lectus nisi, fermentum in risus vitae, rutrum rutrum eros. Sed id ligula hendrerit, finibus leo et, pellentesque turpis. Nunc dapibus malesuada arcu pulvinar pulvinar. Mauris ullamcorper sollicitudin mi at tincidunt. Nam blandit sit amet erat et condimentum. Aliquam erat volutpat. Sed id condimentum turpis. Aliquam ut risus sit amet nisl rhoncus mattis. Fusce vitae erat pharetra, porta elit elementum, aliquam odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque sed malesuada risus, nec ullamcorper diam.

Vivamus tincidunt dictum dui ac accumsan. Donec eget arcu nec augue interdum interdum a id ligula. Phasellus eu tincidunt lacus. Morbi malesuada consequat rhoncus. Morbi eu sapien sit amet orci vestibulum suscipit ac non lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu nunc quis augue luctus vestibulum. Vestibulum lobortis ligula efficitur, viverra leo et, tincidunt elit. Fusce sed luctus ex. Ut a scelerisque massa, vitae rutrum ipsum. Mauris ultricies sodales tortor at gravida.

Integer fermentum id diam sit amet placerat. Aliquam vulputate a turpis sed porttitor. Etiam ultricies felis vitae eros sagittis, vitae molestie turpis rhoncus. Donec porttitor massa sit amet lacinia tincidunt. Aenean molestie laoreet magna ut efficitur. Quisque non quam eu massa maximus varius auctor nec sem. Morbi sed leo lacus.',	'2019-03-14',	2),
(4,	'Lorem Ipsum 4',	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum egestas erat ultricies semper euismod. Integer consectetur viverra egestas. Mauris sit amet orci vel diam tincidunt pretium vel sed lectus. Vivamus eu tristique dui, non elementum velit. Aenean a urna at felis faucibus feugiat eu vestibulum eros. In hac habitasse platea dictumst. Duis odio ante, vehicula sed erat et, aliquam iaculis lectus.

Vivamus tellus urna, lobortis ac nunc in, finibus accumsan ligula. Nulla non turpis lectus. Cras augue mauris, ornare a scelerisque sed, mattis id purus. Nunc nec est scelerisque, dapibus diam at, feugiat quam. Vivamus ut ullamcorper justo. Curabitur interdum mauris eu egestas malesuada. Praesent auctor enim odio, sed interdum arcu ullamcorper ac. Praesent ut auctor nibh, et imperdiet risus. Nunc facilisis vulputate orci eget semper. Nam quis fermentum mi. Praesent interdum justo sem, a aliquet leo pretium nec.

Suspendisse diam enim, fermentum quis maximus et, commodo a tellus. Nam luctus accumsan tincidunt. Morbi ornare nulla auctor lacus feugiat euismod. Sed suscipit at risus id vulputate. Integer venenatis lorem tellus, ac varius risus tincidunt ut. Sed tempus ornare est. In vel tellus at libero sodales sollicitudin eu et leo. In eu sagittis tortor. Vivamus id ante nec mauris suscipit pharetra vitae sed purus. Donec venenatis, quam eget aliquam aliquam, ante ligula vestibulum lacus, nec porttitor odio massa nec sapien. Vivamus aliquam vestibulum nibh, vitae auctor ante. Etiam convallis odio eu pellentesque dignissim. In in massa venenatis, euismod libero non, sodales quam. Maecenas hendrerit condimentum enim blandit vulputate. Donec accumsan urna a rhoncus lobortis. Nullam eget venenatis justo.

Donec consequat lorem et gravida fringilla. Proin a consectetur enim. Donec porttitor, tortor sed iaculis aliquet, leo justo hendrerit urna, nec imperdiet metus diam vitae elit. Suspendisse sollicitudin porttitor rhoncus. Ut laoreet nulla justo, fringilla gravida tortor scelerisque eget. Aenean pulvinar dolor diam. Nulla eleifend venenatis neque, sit amet dictum urna ullamcorper eget. Proin in interdum purus, in mollis augue. Aliquam sollicitudin vestibulum tortor, at egestas sem fermentum sed. Donec dictum lectus sed arcu accumsan pretium.

Maecenas faucibus lacinia sem, nec mollis ligula pulvinar ut. Aliquam erat volutpat. Praesent placerat gravida lacus, dapibus laoreet dui egestas vitae. Nam dignissim, nisi et placerat volutpat, mi enim lacinia tortor, et feugiat magna dolor non tortor. Etiam hendrerit, est nec accumsan ornare, lorem mauris ullamcorper augue, in laoreet dolor dui ac risus. Cras ac nisl hendrerit, blandit velit id, pulvinar lorem. Vestibulum volutpat nibh in ipsum dapibus congue. Cras tristique libero et suscipit lobortis. Ut diam velit, molestie facilisis dui non, euismod luctus lectus. Phasellus sed tristique ante.',	'2019-03-14',	2),
(5,	'Lorem Ipsum 5',	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae justo arcu. Quisque non felis lacus. Cras sollicitudin, tellus ac condimentum accumsan, enim velit egestas risus, ut varius leo lectus et tellus. Donec elementum mi sit amet dui congue lacinia. Pellentesque eget leo nec velit fringilla ultrices. Sed et placerat odio. Morbi pulvinar neque nibh, sit amet faucibus lacus pellentesque et. Nunc malesuada posuere augue, a molestie nunc vehicula vel.

Maecenas eu pellentesque risus. Aenean tincidunt scelerisque magna id tincidunt. Fusce in nibh non felis accumsan laoreet. Sed vitae auctor augue. Vivamus in velit dui. Nunc a dictum turpis. Vestibulum id tincidunt lacus, in euismod libero. Vivamus massa neque, molestie sed finibus blandit, hendrerit fermentum augue. Etiam a sollicitudin ante. Ut eros magna, imperdiet eu pharetra vel, fringilla et libero. Sed velit arcu, egestas a ipsum non, lacinia iaculis mauris.

Pellentesque mollis ullamcorper gravida. Curabitur diam leo, tristique a felis hendrerit, scelerisque interdum diam. Fusce pellentesque, nunc ut finibus mollis, sem tortor varius enim, ut placerat eros quam quis purus. Nullam sed condimentum dui, ac accumsan dui. Nam et justo dui. Nam at augue id nisl accumsan ultricies ut eget tortor. Praesent tincidunt odio vitae augue vestibulum lobortis.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam placerat malesuada mi ac ornare. Curabitur lacinia laoreet lectus. Aliquam sodales aliquam mauris, sit amet elementum magna vulputate eu. Phasellus ullamcorper, risus a fringilla posuere, nisi mauris tincidunt dolor, nec elementum leo metus in massa. Donec vitae leo pharetra, gravida magna nec, tempus ante. Proin vulputate quis diam vel eleifend. Ut lorem nisi, bibendum nec vestibulum vel, dapibus vitae risus. Integer eget erat egestas, viverra mauris vel, sagittis nisi. Suspendisse non luctus eros. Curabitur sed finibus urna, quis tempor metus. Quisque accumsan nec justo eget efficitur. Integer eu cursus magna, sit amet tincidunt dolor. Mauris metus ligula, pretium ac accumsan eget, aliquet ac urna. Duis sed volutpat est.

Quisque sit amet ipsum tempor, facilisis metus ac, venenatis justo. In sit amet congue turpis. Suspendisse potenti. Nullam at molestie dolor, at feugiat diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean mauris velit, vestibulum at venenatis a, condimentum eget orci. Fusce porta odio non porttitor laoreet. Pellentesque nec dignissim sapien. Aenean pulvinar, elit sed commodo tempor, nibh massa congue neque, aliquam maximus felis eros quis justo. Etiam tincidunt nulla sit amet orci consequat, ac fringilla ante rhoncus. Aliquam tincidunt tortor ut consequat imperdiet. In ultricies, enim sit amet imperdiet euismod, nibh augue dictum ligula, vel maximus ipsum erat ac arcu.',	'2019-03-14',	3),
(6,	'Lorem Ipsum 6',	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ligula nisi, faucibus vel turpis vel, rhoncus pharetra quam. Aliquam erat volutpat. Phasellus finibus lacus vel nulla iaculis vehicula. Donec fringilla, libero sed posuere ultrices, nulla mauris aliquam dui, vitae blandit augue dui a eros. Sed euismod nunc id quam convallis, ut egestas est vulputate. Nulla facilisis, lectus sed pretium convallis, sem dui lacinia lectus, quis congue lorem ligula in nibh. Vivamus non bibendum lacus. Aliquam maximus sem rutrum sem interdum bibendum.

Nunc pulvinar felis eu sem congue eleifend. Aliquam vestibulum ut velit sed dapibus. Nam mattis dignissim posuere. Nullam nec elit tellus. Mauris tincidunt tellus congue tortor efficitur, eu venenatis erat aliquam. Vestibulum lobortis scelerisque mauris sed consequat. Donec tincidunt nibh ut nisi cursus, ac placerat tellus commodo. Sed dignissim odio ligula, sed mattis neque sollicitudin at. Etiam non diam velit. Curabitur vestibulum mattis quam vitae tincidunt. Nunc eget sem sapien. Suspendisse dapibus augue sit amet diam placerat malesuada. Etiam porttitor gravida tellus, in rhoncus risus posuere nec. Donec blandit diam vitae orci pulvinar, et eleifend nisi volutpat.

Maecenas vehicula laoreet nunc, vitae dictum turpis mattis elementum. Nunc scelerisque arcu enim, eget suscipit augue bibendum vitae. Integer sagittis est vel ex iaculis, lacinia aliquet nisl sollicitudin. Aenean faucibus lorem in nunc vestibulum consectetur. Ut justo mauris, dapibus id metus vitae, suscipit posuere turpis. Morbi imperdiet ex ac porttitor congue. Nulla venenatis, nulla at dapibus eleifend, odio mauris consectetur sem, in malesuada lorem lorem rhoncus nisl. In ornare maximus mauris. Maecenas vel ullamcorper tellus, quis tempor turpis.

Sed eget imperdiet neque. Suspendisse eget tristique risus. Integer eget augue sed turpis tincidunt sodales. Ut volutpat auctor ante ut volutpat. Cras ultrices est ut ex placerat, id tempus tortor porta. Donec vitae mi orci. In rutrum nibh a nisi pulvinar elementum. Aenean a ullamcorper nisi. Fusce nec eros interdum, tincidunt arcu quis, varius diam. Maecenas nec est ac libero tincidunt hendrerit et a turpis. Cras a sem posuere, fringilla turpis eget, consequat felis. Donec non eros mattis, porta nisi sed, tincidunt neque. Nullam in porttitor magna. Nam condimentum odio tortor, quis iaculis urna facilisis a. Nunc accumsan ex non posuere iaculis.

Donec nisl ipsum, vestibulum dapibus leo nec, elementum placerat nunc. Donec placerat orci vitae est ultricies ullamcorper. Fusce et aliquet quam, vel suscipit diam. Nulla dolor libero, pulvinar a elit pulvinar, pellentesque accumsan diam. Donec efficitur varius dictum. Fusce nec felis varius, tincidunt nisl vestibulum, feugiat augue. Proin eget mattis ante, id imperdiet libero.',	'2019-03-14',	3),
(7,	'Lorem Ipsum 7',	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacus elit, eleifend eu est ut, pellentesque viverra dui. Nunc mollis tincidunt nulla id scelerisque. Aenean commodo arcu in tellus tincidunt interdum. Integer nisi dolor, iaculis sed ex vel, luctus rutrum nibh. Pellentesque vitae vulputate neque, ac interdum tortor. Nulla erat metus, auctor vitae sollicitudin eu, fermentum sed dui. Sed sapien eros, pretium sit amet rutrum et, eleifend in mauris. In ultricies, mi consequat consequat mollis, libero diam suscipit tellus, nec tincidunt erat turpis rhoncus nisi. Donec gravida lacinia mi, vitae ultricies odio. Ut tellus turpis, tempor at tempor ac, malesuada id turpis. Suspendisse pharetra massa et lectus maximus egestas.

Phasellus nunc diam, fringilla ut pulvinar in, congue ut eros. Duis a augue id urna placerat volutpat. Nam eget tortor diam. Morbi a ornare nisl. Maecenas pellentesque nibh vel mauris sollicitudin, vitae tristique sem congue. Etiam non purus mauris. Suspendisse a sagittis justo, id ultrices magna. Ut et tortor non dolor rutrum dapibus posuere eget elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac dolor sed leo hendrerit tincidunt. Pellentesque sit amet feugiat orci. Praesent vitae nisl quis dolor bibendum malesuada et sed lectus. In auctor convallis blandit. Aenean ex magna, convallis at tempor sit amet, tincidunt vitae lacus.

Curabitur eget leo at ex imperdiet cursus. Quisque condimentum aliquam metus, ac imperdiet arcu auctor id. Vivamus sollicitudin laoreet tortor in vulputate. Phasellus vel arcu sed ex placerat varius. Vivamus imperdiet enim a accumsan tristique. Ut interdum vulputate purus vel rhoncus. In finibus ultricies lorem, sed efficitur mi molestie ac.

Nunc massa purus, consequat in maximus sit amet, dictum a mauris. Nullam urna ligula, venenatis et sem viverra, fringilla finibus magna. Etiam condimentum eleifend arcu sit amet bibendum. Proin id massa posuere, ornare tortor tristique, porttitor enim. Phasellus metus urna, posuere at vestibulum non, molestie at purus. Sed quis justo dignissim, porta lorem in, ultrices enim. Curabitur interdum at neque et lobortis. Quisque ac nibh a mauris porta ornare id pharetra neque. Praesent rutrum lectus rutrum ultrices accumsan.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean efficitur metus sollicitudin rhoncus facilisis. In finibus volutpat facilisis. Pellentesque nec tortor quis velit consectetur aliquam. Aliquam dapibus dictum consectetur. Sed tempor velit in pretium consequat. Sed eu libero ac urna viverra faucibus. Nulla hendrerit gravida fermentum. Nunc consectetur massa ut massa malesuada faucibus. Praesent laoreet neque ac tortor congue molestie. Donec sit amet cursus urna. Quisque nec nibh ut metus laoreet blandit. Maecenas porta arcu vulputate dui ultrices imperdiet elementum et diam.',	'2019-03-14',	4),
(8,	'Lorem Ipsum 8',	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sit amet tempor quam, vel feugiat dui. Praesent id sodales sem. In et fermentum libero, eu molestie risus. Cras enim nisl, dictum vitae libero eget, consectetur eleifend urna. Duis sagittis id lectus ut imperdiet. Aliquam erat volutpat. Cras a mi quam.

Suspendisse sit amet malesuada ipsum, sit amet vestibulum odio. Duis non quam ex. Quisque sem massa, ultricies eleifend vulputate et, lacinia eget felis. Mauris lectus erat, vulputate eget congue in, placerat eu odio. Aenean at libero sit amet lacus malesuada rutrum et a sem. Ut porta sit amet mauris eget cursus. Ut ut turpis vel neque placerat pellentesque at a dui. Cras at lacinia turpis, ut interdum magna. Nulla lorem ex, iaculis ut justo a, dictum volutpat massa. Etiam augue justo, efficitur ut tempor id, suscipit feugiat neque.

Mauris vel molestie turpis, vel volutpat mauris. Etiam vel lectus quis massa varius condimentum. In elementum arcu augue, volutpat mollis lectus ullamcorper ut. Vestibulum faucibus quis mauris sit amet vulputate. Maecenas at elit nec elit dapibus accumsan. Maecenas at risus enim. Vestibulum a massa imperdiet, aliquet tellus at, maximus nisl. Aliquam erat volutpat. Quisque euismod enim eu ex mollis sollicitudin.

Etiam pretium luctus odio ut vulputate. Curabitur ut libero venenatis, lobortis ligula ut, vehicula turpis. Proin et faucibus lectus, vel pulvinar magna. Aenean facilisis dolor id hendrerit mattis. Donec fermentum magna non leo sagittis ullamcorper. Pellentesque lobortis et nunc auctor maximus. Vestibulum tortor erat, congue sit amet tortor et, laoreet tempus nibh. Cras in tempor nisl. Nullam dictum quam ut dapibus pretium. Morbi cursus eros vel convallis luctus. Duis tincidunt vel odio a luctus. Aliquam eget magna eu sapien volutpat ullamcorper. Aliquam et sollicitudin diam. Nulla nisi velit, fringilla et urna id, molestie ultrices nulla.

Suspendisse a mi leo. Sed justo justo, tincidunt eget ornare non, iaculis nec magna. Fusce vitae urna eleifend, congue odio ut, efficitur justo. Maecenas finibus dui nec justo semper dictum. Nullam eros sem, vestibulum id lorem eu, accumsan mollis leo. Morbi dapibus quam magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer fringilla mattis nibh ut sodales. Fusce fermentum ex purus, ultricies porttitor massa hendrerit a. Suspendisse sit amet ornare nisl. Phasellus sed purus in ipsum ultricies molestie. Etiam convallis mattis rutrum. Proin scelerisque pulvinar ante nec viverra. Sed elementum commodo velit nec sollicitudin.',	'2019-03-14',	4);
